### ISSUE TITLE
Use fog library for cloud servers

### ISSUE THREAD

**Issue by shtirlic** [kenn/sunzi#2]
There is a great gem FOG (https://github.com/fog/fog) for cloud services with a great API
Supported services http://fog.io/1.1.2/about/supported_services.html

**Comment by kenn** [comment]
Now that Sunzi supports plugins as of v2, the server provisioning feature is spun off as a separate gem as [sunzi](https://github.com/kenn/sunzi-vps).

Infrastructure options are pretty messy right now, and Sunzi will be focused as a configuration automation tool.
