### ISSUE TITLE
Allow file names with leading . within `files` directory

### ISSUE THREAD

**Issue by martinblaha** [kenn/sunzi#42]
Currently if you have a file like .vimrc within the /files directory which you want to copy to your server, this file is being ignored.

The workaround is to remove the . at the beginning and to rename the file later on your server within your recipe.

**Comment by kenn** [comment]
PR welcomed!

**Comment by kenn** [comment]
Dotfiles are included as of v2.1

**Comment by martinblaha** [comment]
This is great news, thank you! :-)
